-- Extended actor registration form fields (Kayıt Formu)
alter table public.actor_profiles
  add column if not exists national_id text,
  add column if not exists birth_place text,
  add column if not exists whatsapp text,
  add column if not exists address text,
  add column if not exists registration_date date default current_date,
  add column if not exists profession text,
  add column if not exists instagram text,
  add column if not exists tshirt_size text,
  add column if not exists pants_size text,
  add column if not exists suit_size text,
  add column if not exists bank_account_name text,
  add column if not exists bank_name text,
  add column if not exists iban text,
  add column if not exists has_passport boolean,
  add column if not exists passport_no text,
  add column if not exists passport_type text,
  add column if not exists visa_countries text,
  add column if not exists has_work_permit boolean,
  add column if not exists has_residence_permit boolean,
  add column if not exists employment_status text[] default '{}',
  add column if not exists sports text[] default '{}',
  add column if not exists dances text[] default '{}',
  add column if not exists model_skills text[] default '{}',
  add column if not exists performance_skills text[] default '{}',
  add column if not exists special_conditions text[] default '{}',
  add column if not exists dances_other text,
  add column if not exists model_other text,
  add column if not exists performance_other text,
  add column if not exists accents text,
  add column if not exists instruments text,
  add column if not exists additional_notes text,
  add column if not exists acting_education text,
  add column if not exists driving_info text,
  add column if not exists availability text,
  add column if not exists other_agency text,
  add column if not exists referral_source text,
  add column if not exists special_interests text,
  add column if not exists kvkk_accepted boolean not null default false,
  add column if not exists registration_completed_at timestamptz;
